name: Generate Space Shooter Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Generate space shooter animation
        uses: czl9707/gh-space-shooter@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          username: Atibayounus
          output-path: 'space-shooter.gif'
          strategy: 'random'
          fps: 40

      - name: Push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add space-shooter.gif
          git commit -m "Update space shooter animation" || echo "No changes"
          git push
